# .github/FUNDING.yml

# GitHub Sponsors — up to 4 usernames
github: [gvinianidzegivi]

# Open Collective slug (change if needed)
open_collective: "preflight-ai"

# Buy Me a Coffee username
buy_me_a_coffee: ""

# thanks.dev username
thanks_dev: ""

# Custom URLs (max 4)
custom:
  - "https://opencollective.com/preflight-ai"
  - "https://github.com/sponsors/gvinianidzegivi"
