# .github/FUNDING.yml

# GitHub Sponsors — up to 4 usernames
github: [gvinianidzegivi]

# Open Collective slug (change if needed)
open_collective: "preflight-ai"

# Patreon username
patreon: "PreflightAI"

